emc4j:
  maven:
    directory: ${user.home}/.m2/repository
#    redirectionsEnabled: true
#    redirect:
#      - groupId: com.treilhes.emc4j
#        artifactId: jfxapps.core.api
#        path: ../../jfxapps.core/jfxapps.core.api/target/classes

#server:
#  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

springdoc:
  show-actuator: true