emc4j:
  registry:
    snapshotsAllowed: true
    defaults:
      samples:
        groupId: com.treilhes.emc4j
        artifactId: emc4j.it.samples.registry
        mandatory: true

  maven:
    directory: ${user.home}/.m2/repository
#    redirectionsEnabled: true
#    redirect:
#      - groupId: com.treilhes.emc4j
#        artifactId: jfxapps.core.api
#        path: ../../jfxapps.core/jfxapps.core.api/target/classes

#server:
#  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

springdoc:
  show-actuator: true