<project xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent/>
    <artifactId>emc4j.boot.starter.test</artifactId>

    <properties>
        <junit.version>5.10.1</junit.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.aop</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.loader</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.context</artifactId>
        </dependency>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.starter.test.dependencies</artifactId>
        </dependency>
    </dependencies>
</project>