<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent/>
    <artifactId>emc4j.it.samples.launcher</artifactId>
    <packaging>jar</packaging>

    <description> Run command: mvn com.treilhes.emc4j:emc4j-maven-plugin:run </description>
    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-maven-plugin</artifactId>
                <version>${revision}</version>
                <configuration>
                    <emc4jVersion>${revision}</emc4jVersion>
                    <debug>false</debug>
                    <profiles>
                        <profile>samples</profile>
                    </profiles>
                    <profileFiles>
                        <profileFile>${basedir}/src/main/resources/application-samples.yaml</profileFile>
                    </profileFiles>
                    <applicationId>00000000-0000-0000-0000-000000000002</applicationId>
                    <javaOptions></javaOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>