<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.treilhes.emc4j</groupId>
        <artifactId>emc4j.it</artifactId>
        <version>${emc4j.version}</version>
    </parent>
    <artifactId>emc4j.it.samples.launcher</artifactId>
    <packaging>jar</packaging>

    <description> Run command: mvn com.treilhes.emc4j:emc4j-maven-plugin:run </description>
    
    <properties>
        <debug>false</debug>
        <debugPort>8000</debugPort>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-maven-plugin</artifactId>
                <version>${emc4j.version}</version>
                <configuration>
                    <emc4jVersion>${emc4j.version}</emc4jVersion>
                    <debug>${debug}</debug>
                    <debugPort>${debugPort}</debugPort>
                    <profiles>
                        <profile>devlookup,samples</profile>
                    </profiles>
                    <applicationId>00000000-0000-0000-0000-000000000002</applicationId>
                    <registry>
                        <groupId>com.treilhes.emc4j</groupId>
                        <artifactId>emc4j.it.samples.registry</artifactId>
                        <version>${emc4j.version}</version>
                    </registry>
                    <javaOptions></javaOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.treilhes.emc4j</groupId>
                        <artifactId>emc4j-maven-plugin</artifactId>
                        <version>${emc4j.version}</version>
                        <configuration>
                            <emc4jVersion>${emc4j.version}</emc4jVersion>
                            <debug>${debug}</debug>
                            <debugPort>${debugPort}</debugPort>
                            <profiles>
                                <profile>devlookup,samples</profile>
                            </profiles>
                            <applicationId>00000000-0000-0000-0000-000000000002</applicationId>
                            <registry>
                                <groupId>com.treilhes.emc4j</groupId>
                                <artifactId>emc4j.it.samples.registry</artifactId>
                                <version>${emc4j.version}</version>
                                <localFolder>${basedir}/src/main/resources/local</localFolder>
                            </registry>
                            <javaOptions></javaOptions>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>