<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.treilhes.emc4j</groupId>
    <artifactId>emc4j.it</artifactId>
    <version>${emc4j.version}</version>
  </parent>
  <artifactId>emc4j.it.samples.registry</artifactId>

  <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-registry-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-registry-resources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>emc4jRegistry</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <format>json</format>
                    <registry>
                        <uuid>4a898b37-d2f7-437a-b4b1-5bd337e5abcf</uuid>
                        <description>
                            <image>sample.png</image>
                            <title>sample applications and plugins Registry</title>
                            <text>Contains all applications and plugins mandatory for running</text>
                        </description>
                        <applications>
                            <application>
                                <uuid>00000000-0000-0000-0000-000000000001</uuid>
                                <splash>sample.png</splash>
                                <dependency>
                                    <groupId>com.treilhes.emc4j</groupId>
                                    <artifactId>root</artifactId>
                                    <version>${emc4j.version}</version>
                                </dependency>
                                <description>
                                    <image>sample.png</image>
                                    <title>Sample root</title>
                                    <text>Sample root description</text>
                                </description>
                                <extensions>
                                    <extension>
                                        <uuid>00000000-0000-0000-0000-000000000011</uuid>
                                        <dependency>
                                            <groupId>com.treilhes.emc4j</groupId>
                                            <artifactId>root-ext1</artifactId>
                                            <version>${emc4j.version}</version>
                                        </dependency>
                                        <extensions>
                                            <extension>
                                                <uuid>00000000-0000-0000-0000-000000000111</uuid>
                                                <dependency>
                                                    <groupId>com.treilhes.emc4j</groupId>
                                                    <artifactId>root-ext1-ext1</artifactId>
                                                    <version>${emc4j.version}</version>
                                                </dependency>
                                            </extension>
                                        </extensions>
                                    </extension>
                                </extensions>
                            </application>
                            <application>
                                <uuid>00000000-0000-0000-0000-000000000002</uuid>
                                <splash>sample.png</splash>
                                <dependency>
                                    <groupId>com.treilhes.emc4j</groupId>
                                    <artifactId>app1</artifactId>
                                    <version>${emc4j.version}</version>
                                </dependency>
                                <description>
                                    <image>sample.png</image>
                                    <title>Sample app1</title>
                                    <text>Sample app1 description</text>
                                </description>
                                <extensions>
                                    <extension>
                                        <uuid>00000000-0000-0000-0000-000000000012</uuid>
                                        <dependency>
                                            <groupId>com.treilhes.emc4j</groupId>
                                            <artifactId>app1-ext1</artifactId>
                                            <version>${emc4j.version}</version>
                                        </dependency>
                                        <extensions>
                                            <extension>
                                                <uuid>00000000-0000-0000-0000-000000000112</uuid>
                                                <dependency>
                                                    <groupId>com.treilhes.emc4j</groupId>
                                                    <artifactId>app1-ext1-ext1</artifactId>
                                                    <version>${emc4j.version}</version>
                                                </dependency>
                                            </extension>
                                        </extensions>
                                    </extension>
                                </extensions>
                            </application>
                        </applications>
                    </registry>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>