<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
  <modelVersion>4.1.0</modelVersion>
  <parent/>
  <artifactId>emc4j.it</artifactId>
  <packaging>pom</packaging>
  <modules>
      <module>emc4j.it.samples</module><!-- must be built first -->
      <module>emc4j.it.samples.registry</module>
      <module>emc4j.it.samples.launcher</module>
      <module>emc4j.it.samples.packager</module>
      <module>emc4j.it.features</module>
      
  </modules>
</project>