<project xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <groupId>com.treilhes.emc4j</groupId>
    <artifactId>emc4j.it.samples</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <subprojects>
        <subproject>root</subproject>
        <subproject>root-ext1</subproject>
        <subproject>root-ext1-ext1</subproject>
        <subproject>app1</subproject>
        <subproject>app1-ext1</subproject>
        <subproject>app1-ext1-ext1</subproject>
    </subprojects>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <emc4j.version>1.0.0-SNAPSHOT</emc4j.version>
        <!--<emc4j.version>${parent.emc4j.version}</emc4j.version>-->
        <!-- compiler 
        <maven-compiler-plugin.version>${parent.maven-compiler-plugin.version}</maven-compiler-plugin.version>
        <maven.compiler.release>${parent.maven.compiler.source}</maven.compiler.release>
        <maven.compiler.source>${parent.maven.compiler.source}</maven.compiler.source>
        <maven.compiler.target>${parent.maven.compiler.target}</maven.compiler.target>-->
        <emc4j.version>1.0.0-SNAPSHOT</emc4j.version>
        <maven-compiler-plugin.version>4.0.0-beta-4</maven-compiler-plugin.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>parent</artifactId>
                <version>${emc4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>