<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
  <modelVersion>4.1.0</modelVersion>
  <parent/>
  <artifactId>emc4j.it.features</artifactId>


    <properties>
        <skip.integration.test>false</skip.integration.test>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.main</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.treilhes.emc4j</groupId>
            <artifactId>emc4j.boot.starter.test.dependencies</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>resolve-jar-path</id>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.treilhes.emc4j</groupId>
                        <artifactId>java.base.patch</artifactId>
                        <version>${revision}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.treilhes.emc4j</groupId>
                        <artifactId>spring.core.patch</artifactId>
                        <version>${revision}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.treilhes.emc4j</groupId>
                        <artifactId>org.hibernate.orm.core.patch</artifactId>
                        <version>${revision}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <skipITs>${skip.integration.test}</skipITs>
                            <useModulePath>true</useModulePath>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <argLine>
                                --patch-module
                                spring.core=${com.treilhes.emc4j:spring.core.patch:jar}
                                --patch-module
                                org.hibernate.orm.core=${com.treilhes.emc4j:org.hibernate.orm.core.patch:jar}
                                --patch-module
                                java.base=${com.treilhes.emc4j:java.base.patch:jar}
                                --add-exports
                                java.base/javapatch.lang.module=java.base.patch.link
                                --add-exports
                                java.base/javapatch.lang.module=ALL-UNNAMED
                                --add-reads
                                org.hibernate.validator=org.apache.tomcat.embed.el
                                --add-exports
                                org.hibernate.validator/org.hibernate.validator.internal.engine=spring.core
                                --add-exports
                                org.hibernate.validator/org.hibernate.validator.internal.constraintvalidators.bv=spring.beans
                                --add-exports
                                org.hibernate.validator/org.hibernate.validator.internal.constraintvalidators.hv=spring.beans
                            </argLine>
                        </configuration>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>